cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', remove_from_cart, name='cart_remove'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import HomeTemplateView, AboutUsView


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', AboutUsView.as_view(), name='about us')

]

products/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('commment/<int:product_id>/', CommentCreateView.as_view(), name='comment_create')
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    pass

cart/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth import get_user_model

# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.PositiveIntegerField(default=0)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='product/product_cover', blank=True)
    date_time_created = models.DateTimeField(auto_now_add=True)
    date_time_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.pk])

class ActiveCommentManager(models.Manager):
    def get_queryset(self):
        return super(ActiveCommentManager, self).get_queryset().filter(active=True)


class Comment(models.Model):
    Product_STARS = (
        ('1', 'Very Bad'),
        ('2', 'Bad'),
        ('3', 'Normal'),
        ('4', 'Good'),
        ('5', 'Perfect')
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')
    body = models.TextField(verbose_name='comment text')
    stars = models.CharField(max_length=10, choices=Product_STARS, verbose_name='comment score')
    date_time_created = models.DateTimeField(auto_now_add=True)
    date_time_modified = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    # Manager
    objects = models.Manager()  # default manager
    active_comment_manager = ActiveCommentManager()

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.product.id])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

cart/forms.py
from django import forms

class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)
    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

products/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body', 'stars')

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages

from .cart import Cart
from .forms import AddToCartProductForm
from products.models import Product

# Create your views here.

def cart_detail_view(request):
    cart = Cart(request)
    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True

        })

    return render(request, 'cart/cart_detail.html', context={'cart': cart})

@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)
    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

        # print(f"form: {form}")
        # print(f"cleaned data: {cleaned_data}")
        # print(f"quantity: {quantity}")

    return redirect('cart:cart_detail')

def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')




pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomeTemplateView(TemplateView):
    template_name = 'home.html'

class AboutUsView(TemplateView):
    template_name = 'pages/aboutus.html'

products/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse
from .models import Product, Comment
from .forms import CommentForm
from cart.forms import AddToCartProductForm
# Create your views here.

class ProductListView(generic.ListView):
    queryset = Product.objects.filter(active=True)
    template_name = 'products/product_list.html'
    context_object_name = 'products'

class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        # context['add_to_cart_form'] = AddToCartProductForm()
        return context

class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    # success_message = "%(calculated_field)s was created successfully"

    # def get_success_url(self):
    #     return reverse('product_list')
    # def get_success_message(self, cleaned_data):
    #     return self.success_message % dict(
    #         cleaned_data,
    #         calculated_field=self.object.calculated_field,
    #     )

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        product_id = self.kwargs['product_id']
        product = get_object_or_404(Product, id=product_id)
        obj.product = product
        # messages.success(self.request, "comment add sucesfuly")

        return super().form_valid(form)

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load comment_tags %}
{% load i18n %}
{% block page_title %}
    {{ product.title }}
{% endblock %}

{% block content %}
{#    <!-- Breadcrumb area Start -->#}
{#    <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-12">#}
{#                    <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">#}
{#                        <h1 class="page-title">سبد خرید</h1>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
    <!-- Breadcrumb area End -->
    <!-- Main Content Wrapper Start -->
    <div class="main-content-wrapper">
        {% include 'top_header.html' with header_name='Cart' %}
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-md--50">
                            <div class="row no-gutters">
                                <div class="col-12">
                                {% if cart %}
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>عکس محصول</th>
                                                <th class="text-left">نام محصول</th>
                                                <th>قیمت</th>
                                                <th>مقدار</th>
                                                <th>مجموع</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in cart %}
                                            <tr>
                                                <td class="product-remove text-left"><a href="{% url 'cart:cart_remove' item.product_obj.id %}"><i
                                                        class="flaticon flaticon-cross"></i></a></td>
                                                <td class="product-thumbnail text-left">
                                                    <img src="assets/img/products/prod-10-70x88.jpg"
                                                         alt="Product Thumnail">
                                                </td>
                                                <td class="product-name wide-column">
                                                    <h3>
                                                        <a href="{% url 'product_detail' item.product_obj.id %}">{{ item.product_obj.title }}</a>
                                                    </h3>
                                                </td>
                                                <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price }} تومان</span>
                                                            </span>
                                                </td>
                                                <td class="product-quantity">
                                                    <form action="{% url 'cart:cart_add' item.product_obj.id %}" method="post">
                                                        {% csrf_token %}
                                                         <div class="quantity">
                                                        <input type="number" class="quantity-input" name="quantity"
                                                               id="qty-1" value="{{ item.quantity }}" min="1">
                                                        {{ item.product_update_quantity_form.inplace }}
                                                             <button type="submit">update</button>
                                                    </div>
                                                    </form>
                                                </td>
                                                <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price }} تومان</span>
                                                            </span>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    {% else %} <p>cart is empty please add some product to the cart | <a href="{% url 'product_list' %}">Go shopping</a></p>
                                {% endif %}
                                </div>
                            </div>
                            <div class="row no-gutters border-top pt--20 mt--20">
                                <div class="col-sm-6 text-sm-right">
                                    <button type="submit" class="cart-form__btn">خالی کردن سبد خرید</button>
                                </div>
                            </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="cart-collaterals">
                            <div class="cart-totals">
                                <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                                <div class="cart-calculator">
                                    <div class="cart-calculator__item">
                                        <div class="cart-calculator__item--head">
                                            <span>مجموع</span>
                                        </div>
                                        <div class="cart-calculator__item--value">
                                            <span>{{ cart.get_total_price }}</span>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                            </div>
                            <a href="checkout.html" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                ثبت سفارش
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content Wrapper Start -->

{% endblock %}

cart/templates/cart/cart_sidebar.html
<!-- Mini Cart Start -->
    <aside class="mini-cart" id="miniCart">
        <div class="mini-cart-wrapper">
            <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="mini-cart-inner">
                <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">سبد خرید</h3>
                <div class="mini-cart__content">
                    <ul class="mini-cart__list text-right">
                        {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="#">
                                    <img src="assets/img/products/prod-1-100x100.jpg" alt="products">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="{% url 'product_detail' item.product_obj.id %}"> {{ item.product_obj.title }} </a>
                                    <a href="#" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{ item.product_obj.price }} تومان</span> &#215; <span>{{ item.quantity }}</span>
                                </span>
                            </div>
                        </li>

                        {% endfor %}


                    </ul>
                    <div class="mini-cart__total">
                        <span>جمع کل</span>
                        <span class="ammount">{{ cart.get_total_price }} تومان</span>
                    </div>
                    <div class="mini-cart__buttons">
                        <a href="{% url 'cart:cart_detail' %}" class="btn btn-fullwidth btn-bg-sand mb--20">مشاهده سبد خرید</a>
                        <a href="checkout.html" class="btn btn-fullwidth btn-bg-sand">پرداخت</a>
                        {{ a }}
                    </div>
                </div>
            </div>
        </div>
    </aside>
    <!-- Mini Cart End -->

pages/templates/pages/aboutus.html
{% extends '_base.html' %}
{% block page_title %}
    about us
{% endblock %}
{% block content %}
    <h1>about us</h1>
{% endblock %}

products/templates/products/product_list.html
{% extends '_base.html' %}
{% block page_title %}
    Product list
{% endblock %}
{% block content %}


    <!-- Preloader Start -->
    {#    <div class="ShoppingYar-preloader active">#}
    {#        <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">#}
    {#            <div class="ShoppingYar-child ShoppingYar-bounce1"></div>#}
    {#            <div class="ShoppingYar-child ShoppingYar-bounce2"></div>#}
    {#            <div class="ShoppingYar-child zuka-bounce3"></div>#}
    {#        </div>#}
    {#    </div>#}
    <!-- Preloader End -->

    <!-- Main Wrapper Start -->
    <div class="wrapper">


        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper container-fluid">
            <div class="shop-page-wrapper shop-fullwidth">
                <div class="container">
                    <div class="row mb--50">
                        <div class="col-12">
                            <div class="shop-toolbar">
                                <div class="container row align-items-center">
                                    <div class="col-lg-12 mb-md--50 mb-xs--10">
                                        <div class="shop-toolbar__left d-flex align-items-sm-center align-items-start flex-sm-row flex-column">
                                            <p class="product-pages">نمایش ۱-۲۰ از ۴۹</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid shop-products">
                    <div class="row">
                        <div class="col-12">
                            <div class="tab-content" id="product-tab-content">
                                <div class="tab-pane fade show active" id="nav-all">
                                    <div class="row xxl-block-grid-6 grid-space-20">
                                        {% for product in products %}
                                            <div class="col-xl-3 col-md-4 col-sm-6 mb--50">
                                                <div class="ShoppingYar-product">
                                                    <div class="product-inner">
                                                        <figure class="product-image">
                                                            <a href="{{ product.get_absolute_url }}">
                                                                {% if product.image %}
                                                                <img src="{{ product.image.url }}">
                                                                {% endif %}
                                                            </a>
                                                            <div class="ShoppingYar-product-action">
                                                                <div class="product-action d-flex">
                                                                    <a href="wishlist.html" class="action-btn">
                                                                        <i class="flaticon flaticon-like"></i>
                                                                    </a>
                                                                </div>
                                                            </div>
                                                        </figure>
                                                        <div class="product-info">
                                                            <h3 class="product-title mb--15">
                                                                <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                                            </h3>
                                                            <div class="product-price-wrapper mb--30">
                                                                <span class="money">{{ product.price }} تومان</span>
                                                            </div>
                                                            <a href="cart.html"
                                                               class="btn btn-small btn-bg-sand btn-color-dark px-3">اضافه
                                                                کردن به سبد خرید</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                        {#                                        <div class="col-xl-3 col-md-4 col-sm-6 mb--50">#}
                                        {#                                            <div class="ShoppingYar-product">#}
                                        {#                                                <div class="product-inner">#}
                                        {#                                                    <figure class="product-image">#}
                                        {#                                                        <a href="product-details.html">#}
                                        {#                                                            <img src="https://dkstatics-public.digikala.com/digikala-products/15d774761e234a15c1c559ac540963baad9e229f_1631704695.jpg?x-oss-process=image/resize,m_lfit,h_800,w_800/quality,q_90"#}
                                        {#                                                                 alt="Products">#}
                                        {#                                                        </a>#}
                                        {#                                                        <div class="ShoppingYar-product-action">#}
                                        {#                                                            <div class="product-action d-flex">#}
                                        {#                                                                <a href="wishlist.html" class="action-btn">#}
                                        {#                                                                    <i class="flaticon flaticon-like"></i>#}
                                        {#                                                                </a>#}
                                        {#                                                            </div>#}
                                        {#                                                        </div>#}
                                        {#                                                        <span class="product-badge">تخفیف ویژه</span>#}
                                        {#                                                    </figure>#}
                                        {#                                                    <div class="product-info">#}
                                        {#                                                        <h3 class="product-title h6 mb--15">#}
                                        {#                                                            <a href="product-details.html">{{ product.title }}</a>#}
                                        {#                                                        </h3>#}
                                        {#                                                        <div class="product-price-wrapper mb--30">#}
                                        {#                                                            <span class="money text-success">{{ product.price }} تومان</span>#}
                                        {#                                                            <span class="money-separator">-</span>#}
                                        {#                                                            <span class="old-price text-danger">#}
                                        {#                                                                <span class="money text-danger">۸۰,۰۰۰ تومان</span>#}
                                        {#                                                            </span>#}
                                        {#                                                        </div>#}
                                        {#                                                        <a href="cart.html"#}
                                        {#                                                           class="btn btn-small btn-bg-sand btn-color-dark px-3">اضافه#}
                                        {#                                                            کردن به سبد خرید</a>#}
                                        {#                                                    </div>#}
                                        {#                                                </div>#}
                                        {#                                            </div>#}
                                        {##}
                                        {#                                        </div>#}
                                    </div>
                                </div>
                            </div>
                            <nav class="pagination-wrap mt--35 mt-md--25 pb-5">
                                <ul class="pagination">
                                    <li><a href="#" class="next page-number"><i
                                            class="fa fa-angle-double-right"></i></a></li>
                                    <li><span class="current page-number">1</span></li>
                                    <li><a href="#" class="page-number">2</a></li>
                                    <li><a href="#" class="page-number">3</a></li>
                                    <li><a href="#" class="prev page-number"><i class="fa fa-angle-double-left"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->

        <!-- Footer Start-->
        <footer class="footer">
            <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-9 text-center">
                            <div class="footer-widget mb--50">
                                <div class="textwidget">
                                    <img src="assets/img/codingyar_logo.png" alt="Logo">
                                </div>
                            </div>
                            <div class="footer-widget mb--50 pb--1">
                                <ul class="footer-menu">
                                    <li><a href="">درباره ما</a></li>
                                    <li><a href="">قوانین و مقررات</a></li>
                                    <li><a href="">تماس با ما</a></li>
                                </ul>
                            </div>
                            <div class="footer-widget">
                                Codingyar.com © | all rights reserved
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End-->

        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>در باکس زیر عبارت خود را وارد کنید</p>
                <form class="searchform">
                    <input type="text" name="popup-search" id="popup-search" class="searchform__input"
                           placeholder="جستجو در بین محصولات...">
                    <button type="submit" class="searchform__submit"><i
                            class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->

       {% include 'cart/cart_sidebar.html' %}

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->


    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="assets/js/vendor.js"></script>

    <!-- Main JS -->
    <script src="assets/js/main.js"></script>

{% endblock %}

templates/home.html
{% extends '_base.html' %}
{% block page_title %}
Home page
{% endblock %}
{% block content %}
<h1>Home page</h1>
{% endblock %}

templates/top_header.html
 <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                            <h1 class="page-title">{{ header_name }}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>